# Generated by Django 3.2.17 on 2024-01-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('duration_type', models.CharField(choices=[('year', 'Year'), ('semester', 'Semester')], max_length=10)),
                ('course_type', models.CharField(choices=[('internal', 'internal'), ('external', 'external')], max_length=10)),
                ('duration', models.IntegerField()),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_or_semester', models.IntegerField()),
                ('internal_max_marks', models.IntegerField()),
                ('internal_min_marks', models.IntegerField()),
                ('external_max_marks', models.IntegerField()),
                ('external_min_marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('enrollment_year', models.CharField(default=2024, max_length=4)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('personal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('photo', models.BinaryField()),
                ('signature', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('photo', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_link', models.CharField(max_length=250, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(max_length=20)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('result_status', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.IntegerField()),
                ('external_marks', models.IntegerField()),
                ('total_mm', models.IntegerField()),
                ('total_mo', models.IntegerField()),
                ('remark', models.CharField(default='PASS', max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.result')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.coursesubject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.session'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('admit_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_year', models.PositiveSmallIntegerField()),
                ('year_or_semester', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursesubject',
            unique_together={('course', 'subject', 'year_or_semester')},
        ),
    ]
