# Generated by Django 4.1.6 on 2023-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total_mm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_mo',
            field=models.IntegerField(default=50),
        ),
    ]
