# Generated by Django 4.1.6 on 2023-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsite', '0002_marks_total_mm_marks_total_mo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='total_mm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_mo',
            field=models.IntegerField(),
        ),
    ]
